### ISSUE TITLE
UX - Duplicate Bower & NPM Packages

### ISSUE THREAD

**Issue by itzg** [webjars/webjars#1014]
When using "Add a New Bower WebJar" to update angularjs to v1.3.15 it failed with the message:

Version 1.3.15 for path 'webjars/maven/org.webjars.bower:angulerjs already exists

Here's the dialog usage:
![000167_10_18_webjars - bower webjars](https://cloud.githubusercontent.com/assets/988985/7670933/2048fd9c-fc7e-11e4-846c-e7eded9898a6.png)

And the available list of versions:
![image](https://cloud.githubusercontent.com/assets/988985/7670937/4340ddec-fc7e-11e4-81f0-58bae0f75a83.png)

**Comment by itzg** [comment]
...ah, there's two "angular" modules. The "angular" modules supplies 1.3.15.

![000168_10_38_webjars - bower webjars](https://cloud.githubusercontent.com/assets/988985/7671010/fcdbf302-fc80-11e4-8a22-665a367f1384.png)

**Comment by jamesward** [comment]
Thanks for reporting this.  There is a usability issue that we need to fix.  The problem stems from Bower allowing multiple packages pointing to the same repo.  Originally I was collapsing these down to a single package but that didn't work because there isn't a canonical name anywhere and then the `artifactId` wouldn't match the `bower install x` syntax.  So now we have duplicates.

I'm going to re-open this.  Any ideas on how to improve the usability?

**Comment by itzg** [comment]
Ah, I see what you mean. The [Bower package.json](https://github.com/angular/bower-angular/blob/master/package.json#L2) is close, but misaligned by `name`, when comparing to [origin repo](https://github.com/angular/angular.js/blob/master/package.json#L2). What adds to the silliness is that bower natively uses the `bower.json`

So, it seems the originating repo URL is the only canonical identifier. 

    //github.com/angular/angular.js.git

At least that matches up between the two `package.json` files above.

Let me ask a question back: is the "Bower WebJars" named "Bower" in the spirit of mirroring the Bower packages or leveraging the `bower.json` spec? (If the first, that actually makes a lot of sense to me since they've already formed a unified catalog.) I guess in either case, the Bower package name of `angular` would "win".

**Comment by itzg** [comment]
Digging into Bower's site I see their source component list itself contains ambiguous entries

```
> curl https://bower-component-list.herokuapp.com | jq .[].name | egrep "\"angular(js)?\""
"angular"
"angularjs"
```

**Comment by jamesward** [comment]
Well it gets trickier than that.  The `name` in `bower.json` is arbitrary.  The [Bower index](https://bower-component-list.herokuapp.com/) is where the `bower install x` name comes from.  And if you search through there you will see a bunch of different packages registered under different names, all pointing to the same git repo.

**Comment by jamesward** [comment]
> Digging into Bower's site I see their source component list itself contains ambiguous entries

Ah, yes, you found the source of the ambiguity also.  :)

The [Bower Search](http://bower.io/search) has a blacklist and some other tricks in their JS code that I can't replicate in a maintainable way for Bower WebJars.

I think that they plan on cleaning up their repo at some point.  But it is going to be tough since removing the duplicates will break a bunch of stuff.  So for now I think we have to continue publishing under the duplicate names and fix the UI somehow (the same approach bower.io took).  BTW: There might also be transitive deps that use these duplicate names which is another reason we'd need to have the different artifactIds.

**Comment by itzg** [comment]
Looks like you might be actively fiddling with it since there's now 2 of "angular" :)
![image](https://cloud.githubusercontent.com/assets/988985/7672225/e7ae9b68-fcaf-11e4-89a6-ebde316912bc.png)


...and it looks like you're going down a path I was going to suggest. Take a given package name and then disambiguate it by dipping into the "website" and grabbing the `name` of the `$website/bower.json`. That's given the overlap I saw of:

```
$ jq '.[] | select(.name == "angular" or .name == "angularjs")' components.json
{
  "keywords": [
    "angular",
    "framework",
    "browser",
    "client-side"
  ],
  "name": "angular",
  "description": "Bower package for AngularJS",
  "owner": "angular",
  "website": "https://github.com/angular/bower-angular",
  "forks": 143,
  "stars": 117,
  "created": "2012-09-10T14:57:07Z",
  "updated": "2015-05-14T21:15:51Z"
}
{
  "keywords": [
    "angular",
    "framework",
    "browser",
    "client-side"
  ],
  "name": "angularjs",
  "description": "Bower package for AngularJS",
  "owner": "angular",
  "website": "https://github.com/angular/bower-angular",
  "forks": 143,
  "stars": 117,
  "created": "2012-09-10T14:57:07Z",
  "updated": "2015-05-14T21:15:51Z"
}
```

**Comment by itzg** [comment]
nm, there were 2 before :)

**Comment by jamesward** [comment]
I think this is as good as I can make it for now.  So I'm going to close this unless there is something else someone comes up with for a better UI.

**Comment by itzg** [comment]
I do like the choice of NPM vs Bower style packaging. So far that has covered the cases I have encountered. Thanks.
