### ISSUE TITLE
[NPM] Corrupted uploads

### ISSUE THREAD

**Issue by Lykathia** [webjars/webjars#1040]
lodash.toplainobject: 3.0.0
debug: 0.7.4

Unsure what is causing the issue, but these two packages are coming back with:

```
Failed! Version 3.0.0 for path 'webjars/maven/org.webjars.npm:lodash.toplainobject already exists If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues 
Created BinTray Package
Converted project licenses
Created NPM WebJar
Fetched NPM tgz
Generated POM
Converted dependencies to Maven
Got NPM info
Starting Deploy
```

although are not published. I'm guessing they corrupted or timed out on upload and need to be repushed, but not entirely sure.

**Comment by jamesward** [comment]
Sometimes there is a failure after the package has been created.  And I don't have logic to handle a retry yet.  See #1025

`debug` `0.7.4` failed because the license could not be determined but Bintray didn't fail since the package had already been created with a valid license.  I need to add logic to fail earlier if there isn't a valid license.  And we need to see why a license could not be detected for that version.

For some reason `lodash.toplainobject` `3.0.0` was not added to jCenter automatically so it didn't deploy.  I'm manually handling that one.

**Comment by jamesward** [comment]
`lodash.toplainobject` `3.0.0` has been deployed to Maven Central but might take a little why to be available.
