### ISSUE TITLE
[NPM] Dependencies can include links to git repositories

### ISSUE THREAD

**Issue by Lykathia** [webjars/webjars#1044]
https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

Some node packages (such as [engine.io](https://github.com/Automattic/engine.io)) declare dependencies to specific commits in git repos, or to URL's containing a tarball.

If this isn't going to be supported in WebJars, should atleast warn the user when uploading a WebJar that it won't be able to have it's dependencies resolved.

**Comment by jamesward** [comment]
I'm still not quite sure how to handle this but I'm glad we have an open issue for this.  As I mentioned somewhere earlier we could have an `org.webjars.git` groupId for deploying git-based packages.  If we did that we could compile the package (whatever it is) so we have a real binary release (and use the src package for the original).  I wouldn't want to do this for anything but tags and commit ids since released artifacts should be immutable.  But this is definitely possible.

Personally I'd rather that repos like NPM adopt a stance like Maven Central where packages in a repo can only depend on other packages in the repo because this is the only way to insure reproducible builds.  But I don't control NPM so that might be boiling the ocean.

What do you think?

**Comment by Lykathia** [comment]
Yeah, I think it's a bit too ambitious to try and change the node world. The power that is deploying directly from a git tag is something I've used a bunch with python/pip, and it can really help, especially when trying to get things done in legacy enterprise environments. I don't see any compelling reason for NPM to add more rigor around that area.

In cases where packages have some dependency on a github repo, should probably just create a classic webjar and save the headache.

The org.webjars.git idea is interesting. It would fall down when trying to have semantic versioning tho, unless it was deploying off of tags that were versioned.

I'd be in favor for a more explicit error message around this, and just leaving it as an exercise to the reader -- if it turns out to be a pain point, could revisit.

As an afterthought, perhaps there is a way to "fatjar" that dependency into the webjar at creation, so it doesn't become a dependency, but part of the source. That could get messy with all the possible transitive dependencies, and node has no guarantee against cyclic dependencies.

¯\_(ツ)_/¯

**Comment by jamesward** [comment]
WebJars don't have to follow SemVer.  We have a bunch of Classic WebJars that use short git commit hashes as the version.  So that part is totally doable.

**Comment by jamesward** [comment]
I've run into a hurdle with this.  I need to be able to resolve a git url to a unique artifact id because the `name` property in the `package.json` is not globally unique.  I'm not quite sure what to do about this.  Git URLs will be like `git://foo.com/bar.git` or `https://foo.com/bar.git` or `https://github.com/foo/bar.git`.

The best I can come up with is to turn those URLs into valid artifactIds like:

    git://foo.com/bar.git -> foo-com-bar

Kinda messy but I can't think of another way to do this.

Any thoughts?

**Comment by Lykathia** [comment]
Yeah, that can get pretty messy.
Missing is BitBucket (bitbucket.org:foo/bar.git), which would have to behave like GitHub.

In general:

`git://(foo).(com)/(bar/baz).git => \2.\1.\3` with any /'s turned into dashes?

```
org.webjars.npm.com-github-user-repo
org.webjars.npm.com-bitbucket-user-repo
org.webjars.npm.org-example-repo
```

Not the worst thing in the world, it's repeatable and explicit about origin.

**Comment by jamesward** [comment]
Cool.  Thanks for the feedback!

Here is the diff of my current progress:
https://github.com/webjars/webjars/compare/master...gitwebjars

**Comment by jamesward** [comment]
I think this is pretty close.  Both Bower & NPM WebJars can be created from git repos.  Dependency definitions which include references to git repos will work but the dependencies will still need to be manually deployed.

**Comment by Lykathia** [comment]
Brave man. /applauds

To clarify, the manual deployment of dependencies is still the same as it is now for any npm dependencies anyway, yeah?

**Comment by jamesward** [comment]
Yup. That is right.  I'd like to automate deployment of dependencies but it gets a bit tricky with preventing circular dependencies.

**Comment by jamesward** [comment]
This should be deployed in 15 minutes or so.  Hopefully I didn't break anything.  :)
