### ISSUE TITLE
Dependency of angular-ui-ace is not resolved

### ISSUE THREAD

**Issue by cornerman** [webjars/webjars#1051]
Installing angular-ui-ace fails, because ace-builds cannot be resolved. Installation via bower works fine.

```
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.webjars.bower:ace-builds:[1.0.0,2)
[warn] 		  +- org.webjars.bower:angular-ui-ace:0.2.3
```

**Comment by jamesward** [comment]
Hmmm...  I'm perplexed.  I can do a `bower install ace-builds` but the package isn't found in the Bower index: https://bower-component-list.herokuapp.com/

I'm not sure what is going on here.  Any ideas?

**Comment by cornerman** [comment]
The only thing I found was that the [ace-builds repository](https://github.com/ajaxorg/ace-builds) does not actually have a bower.json file. But how is it registered with bower then?

**Comment by jamesward** [comment]
I was able to get the package info through: https://bower-as-a-service.herokuapp.com/info/ace-builds

You can see that the upstream repo is: https://github.com/ajaxorg/ace-builds

Because the webjars.org UI makes you select from something in the index, but the backend service doesn't, I was able to publish the WebJar manually.  It will take up to a few hours to sync but then I think this should work.

Leaving this open awaiting verification.

**Comment by cornerman** [comment]
Thanks for the quick response; this works in principle, but only an old version (v1.0.0) of ace-builds is available. Could you manually deploy the newest version (v1.1.9)? I need features of the newer version and angular-ui-ace only specifies the major version of ace-builds.

**Comment by jamesward** [comment]
Deploying that version now.

In the meantime you might want to file an issue with upstream project about them not showing up in the Bower index.

**Comment by cornerman** [comment]
Works now :)

**Comment by jamesward** [comment]
Great!
