### ISSUE TITLE
angular-new-router (WebJars npm)

### ISSUE THREAD

**Issue by RBleyenberg** [webjars/webjars#1063]
Failed! Could not convert npm version to maven for: route-recognizer git://github.com/btford/route-recognizer If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Got NPM info Starting Deploy

**Comment by jamesward** [comment]
Unfortunately this library contains a dependency on something which is not a published NPM artifact:
https://github.com/angular/router/blob/master/package.json#L16

This isn't supported by NPM WebJars at this time since NPM WebJars are for artifacts published in NPM.  We have plans to support git-based artifacts in the future: #1044
