### ISSUE TITLE
Failed to deploy angular-smart-table

### ISSUE THREAD

**Issue by stanleyxu2005** [webjars/webjars#1073]
I tried to deploy `angular-smart-table` 2.1.0 via bower, but it fails because their `bower.json` has `"angular":"latest"` instead of a specified version. Is it possible to replace `"latest"` to a valid version from webjar side?

Here is the raw output:
```
Failed! Could not convert npm version to maven for: angular latest If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Got Bower info Starting Deploy
```

**Comment by jamesward** [comment]
Hmm...  These totally indeterminate dependencies are so bad.  Ideally this would be fixed by the upstream project.  We *could* convert `latest` to `[0,)` but that is just so nasty.  I mean is `angular-smart-table` really compatible with any version of `angular` now, into infinity?  I doubt it.  Or does `latest` mean that `angular-smart-table` is only compatible with the version of `angular` that is the `latest` right at this moment?  And what moment are we talking about?  The moment I run the build or the moment the author ran the build?  Or any moment in time?

So as you can see, my strong preference would be to get `angular-smart-table` to specify some kind of actual semantic compatibility.

**Comment by stanleyxu2005** [comment]
I dont know if the component author will do the change. I'd suggest webjars provides the possibility to understand invalid version pattern. There are many libraries out there that might have the same problem. Convince their authors to make a change is not always with luck.

**Comment by jamesward** [comment]
Hmm... Maybe if we leave off the version from a dependency in the `pom.xml`, that will be the same thing as `latest`.
