### ISSUE TITLE
Unable to deploy font-awesome 4.4.0 from npm

### ISSUE THREAD

**Issue by kreyssel** [webjars/webjars#1167]
I try to deploy font-awesome 4.4.0 from npm but i got a "no valid licenses found" error.

Is "OFL-1.1 AND MIT" license really not valid bintray licenses?

If it true - why is version 4.3.0 already deployed?

Thanks again. :)

The full log
```
Failed!
No valid licenses found. Detected licenses: OFL-1.1 AND MIT
The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1
License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo.
Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.
           
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
            
Created NPM WebJar
Fetched NPM tgz
Generated POM
Converted dependencies to Maven
Got NPM info
Determined Artifact Name: font-awesome
Starting Deploy
```

**Comment by jamesward** [comment]
I think it was a mistake that `4.3.0` was published because Maven Central doesn't have a concept of an `AND` for licenses.  You can see that both licenses are included in the `pom.xml`:
https://search.maven.org/#artifactdetails%7Corg.webjars.npm%7Cfont-awesome%7C4.3.0%7Cjar

But this means `OR` in Maven POM land.

I don't think we can fix this.  For more details see: #1127
