### ISSUE TITLE
Allow to deploy github bower packages

### ISSUE THREAD

**Issue by mdedetrich** [webjars/webjars#1171]
As is standard practice in bower land, when a user needs to patch a library (due to a security issue or quick bug fix), and it hasn't been pushed to upstream yet, you have the ability to specify a bower dependency by a github repo, i.e.

```json
{
  "name": "some-project",
  "version": "0.0.1",
  "dependencies": {
      "requirejs-plugins": "git://github.com/mdedetrich/requirejs-plugins#jsonSecurityVulnerability"
  }
}
```

Would it be possible for webjars bower deployment to work with github repos like the above? I assume it would work just like the standard webjar deploy, except that it would use some github prefix to differentiate itself from the official bower deployment.

**Comment by jamesward** [comment]
This was implemented recently but hasn't been extensively tested yet.  Here is the conversation: https://github.com/webjars/webjars/issues/1044

You should be able to deploy any Bower or NPM package from a git repo by specifying the repo url in either the Bower or NPM form on webjars.org.  Let me know if that works for you.

**Comment by mdedetrich** [comment]
I tried this and it wasn't working. The url I am using is `git://github.com/mdedetrich/requirejs-plugins#jsonSecurityVulnerability`, and its just stuck on Starting Deploy

**Comment by jamesward** [comment]
I think the problem was the `#` which I should add handling for.  But when I removed it I got an error:
```
Failed! JsResultException(errors:List((/homepage,List(ValidationError(error.path.missing,WrappedArray()))))) If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Determined Artifact Name: github-com-mdedetrich-requirejs-plugins Starting Deploy
```

The `homepage` property in the `bower.json` is required.  We can try to semantically determine it in this case.  So there are a few things I'll need to work on here.

Thanks for giving it a try!

**Comment by mdedetrich** [comment]
No problem!

**Comment by jamesward** [comment]
On other issue I noticed is that `jsonSecurityVulnerability` is a branch not a tag.  So far we've only used tags for releases since they point to a point-in-time.  A branch is not and thus not compatible with an immutable release.  So I'm not sure how to handle this.  Maven has a way of doing mutable releases via `SNAPSHOT` releases.  We could go that route but it requires the user to add another resolver.  Or we could stick with just tags and ask upstream libraries to tag a release.  What do you think?

**Comment by mdedetrich** [comment]
I suppose its a question of whether you want to support what bower supports, or if you want to support what maven supports.

The above is technically a valid bower dependency, so I suppose (as you state), you should be using the maven equivalent, which is `SNAPSHOT`. Does Bintray not have support for SNAPSHOTs?

A suppose an alternative would be to make a hash out of the date of the last commit

**Comment by mdedetrich** [comment]
Now that I think about it, making a hash of the timestamp of the latest commit could work, as that will provide an immutable version for that specific branch

**Comment by jamesward** [comment]
Instead of a SNAPSHOT I like the idea of using the commit sha as the version.  I think that will work.  I'll work on a fix that does that.

**Comment by mdedetrich** [comment]
@jamesward Is there an update on this (only reason I am asking is it is blocking something at work). If you don't have the time I am more than comfortable doing a PR myself if you can point me to the right direction.

**Comment by jamesward** [comment]
This change should be deployed in about 10 minutes.  You can try it by entering a git repo with a branch into the package name input field, e.g. git://github.com/mdedetrich/requirejs-plugins#jsonSecurityVulnerability

Then select the commit you want to deploy.

However, I don't think that particular one will actually deploy because it doesn't have any license metadata in it.

Let me know if you have any issues.

**Comment by mdedetrich** [comment]
@jamesward Thanks heaps, will look into it. Since that pull request happens to be my branch, I can add a LICENSE file so its valid, so that shouldn't be too much of a problem.

Will let you know if there are any issues

**Comment by jamesward** [comment]
Cool.  Deployment is taking a bit longer because a test timed out on Travis.  Trying to kick it...

**Comment by jamesward** [comment]
Looks like all of the tests passed so this will be deployed shortly.

**Comment by jamesward** [comment]
Oh, and you might run into this: https://github.com/webjars/webjars/issues/1196

**Comment by mdedetrich** [comment]
Sorry for taking ages to get back, have been really easy, but it still doesn't appear to be working

<img width="601" alt="screen shot 2015-10-27 at 12 30 14 pm" src="https://cloud.githubusercontent.com/assets/2337269/10747202/9e84e0e2-7ca6-11e5-807f-b4932e8d553b.png">

It seems I am unable view the commits. I have also synced with upstream so there is a valid LICENSE.txt file in that commit

**Comment by jamesward** [comment]
@mdedetrich I've pushed a change that I think should fix this.  It should be deployed in about 15 minutes.  Let me know if it works.  Thanks!

**Comment by mdedetrich** [comment]
Now getting a license error even though there is a `LICENSE.txt` file there, however it is now listing the commits properly, getting there!

<img width="599" alt="screen shot 2015-11-03 at 10 49 05 am" src="https://cloud.githubusercontent.com/assets/2337269/10897815/babd4db8-8218-11e5-8f2c-ddfd22096213.png">

**Comment by jamesward** [comment]
Looks like I need to fix #1229 for this.  Stay tuned.

**Comment by jamesward** [comment]
This should be deployed.  Let me know how it goes.

**Comment by mdedetrich** [comment]
Working now, thanks!
