### ISSUE TITLE
Failing: bower zeroclipboard (dependency of handsontable 0.17.0)

### ISSUE THREAD

**Issue by nafg** [webjars/webjars#1191]
```
Failed!
<!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
            
Determined Artifact Name: zeroclipboard
Starting Deploy
```

Arguably it shouldn't have published handsontable without first publishing its dependencies automatically...
Also why do the logs get prepended to the top, the opposite of a console?

Anyway I hope you can fix the failure.
Thanks

**Comment by jamesward** [comment]
There is an issue already for auto-transitive deployment: #1186

As far as the prepending goes...  That is probably just me being lazy.  Cause if I append then I need to also scroll to the bottom.  Want to send a PR for that?

I'm not sure why this lib is failing deployment.  I'll investigate.

**Comment by jamesward** [comment]
The license detection fails because the license from [the metadata](https://bower-as-a-service.herokuapp.com/info/zeroclipboard/2.2.0) points to: 
https://github.com/zeroclipboard/zeroclipboard/blob/master/LICENSE

And unfortunately we can't easily figure out the actual license from that URL because it is a bunch of HTML.

A few ideas...
- Maybe we can fallback to the GitHub License service which would use the text-based LICENSE in that repo.
- Maybe we can detect that the file is HTML and figure out a way to get the text version.
