### ISSUE TITLE
NPM deploy fails to detect license for ms

### ISSUE THREAD

**Issue by jochenberger** [webjars/webjars#1229]
Trying to deploy ms:0.7.1 from www.webjars.org/npm fails: No valid licenses found. No licenses were found.
There's a `package.json` as well as a `LICENSE` file specifying the MIT license for the package.

**Comment by jamesward** [comment]
Unfortunately the tagged `package.json` does not have a specified `license`: https://github.com/rauchg/ms.js/blob/0.7.1/package.json

It also doesn't have a `homepage` specified so we don't know where to go look for a `LICENSE`.  Since this repo has the `license` specified in `master` maybe they can do a new release with that.

**Comment by jochenberger** [comment]
> It also doesn't have a homepage specified so we don't know where to go look for a LICENSE.

Oh, I misunderstood the docs then, I thought the repo would be checked for a `LICENSE`, that's why I wondered what goes wrong.

**Comment by jamesward** [comment]
We could try to get the LICENSE from the git repo...

**Comment by jamesward** [comment]
This should be deployed in about 15 minutes.  Feel free to reopen if it still doesn't work.
