### ISSUE TITLE
Corrupt file: droid-sans-v6-latin-700.eot

### ISSUE THREAD

**Issue by the-james-burton** [webjars/webjars#1248]
This issue follows on from https://github.com/swagger-api/swagger-ui/issues/1728

I believe this file has a corrupt file inside it...
http://repo1.maven.org/maven2/org/webjars/swagger-ui/2.1.2/swagger-ui-2.1.2.jar 

This is the file that I believe to be corrupt...
http://cdn.jsdelivr.net/webjars/org.webjars/swagger-ui/2.1.2/fonts/droid-sans-v6-latin-700.eot 

The swagger-ui project suggested I raise an issue with you.

Can you help get this font fixed?

**Comment by jamesward** [comment]
This WebJar just repackages the upstream release from: https://codeload.github.com/swagger-api/swagger-ui/zip/v2.1.2

So that file should be the exact same as the one in that zip.  I looked at the files in the WebJar and the files in the upstream zip and they seem to be identical.  So I think that your issue exists with the upstream project.

**Comment by the-james-burton** [comment]
Ok, thanks. I will raise another issue with the swagger-ui team.
