### ISSUE TITLE
Issue adding polymer elements using maven

### ISSUE THREAD

**Issue by chevdor** [webjars/webjars#1249]
I have included several webjars successfully using maven:
 - webcomponentsjs
 - polymer
 - bootstrap
All went fine.

I am running into an issue trying to add polymer elements. I have tried a few and I mostly get errors:
paper-button
```Missing artifact org.webjars.bower:github-com-PolymerElements-paper-button:jar:1.0.3```

paper-checkbox
```Missing artifact org.springframework:spring-expression:jar:4.2.2.RELEASE```

I also tried the iron-elements:
```
No versions available for org.webjars.bower:github-com-PolymerElements-iron-image:jar:[1.0.0,2) within specified range

org.eclipse.aether.resolution.VersionRangeResolutionException: No versions available for org.webjars.bower:github-com-PolymerElements-iron-image:jar:[1.0.0,2) within specified range
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.filterVersions(DefaultDependencyCollector.java:648)
	at 
...
```

**Comment by jamesward** [comment]
This is probably because some of the Bower WebJar dependencies haven't been created yet.  You can try to [do that yourself](http://webjars.org/bower) or file issues for each one you need.

If you decide to do it yourself there is a convention you will need to know about with these...  
Notice that `org.webjars.bower:github-com-PolymerElements-paper-button:jar:1.0.3` is different than the usual.  This is because the dependency was specified as a git repo, not another Bower artifact.  So if you want to deploy that one, use the following: `https://github.com/PolymerElements/paper-button.git`

Let me know how that goes.

BTW: We are hoping to handle automatic transitive dependencies in the future: #1186

**Comment by chevdor** [comment]
I understand your explanation for the 3rd problem but I don´t understand the 2 first issues. I discovered webjars (great great job btw) yesterday and I am trying to figure what is an error on my side or a real issue.

For instance paper-button *is* available (twice actually) as bower webjar so I don´t understand why added paper-button reports an issue saying that paper-button is missing.

The springframework issue is likely a mistake on my side however, I do have ```org.springframework:spring-expression:jar:4.2.2.RELEASE```in my dependency list in maven.

**Comment by jamesward** [comment]
What errors are you getting now?
