### ISSUE TITLE
Polymer WebJars

### ISSUE THREAD

**Issue by iphydf** [webjars/webjars#1257]
I've spent a couple of hours adding all the PolymerElements packages to webjars, but now the problem is that they are extracted into `github-com-PolymerElements-$package` instead of `$package`, so nothing can find them.

This is also an issue for jsdelivr, e.g.:
https://cdn.jsdelivr.net/webjars/org.webjars.bower/github-com-PolymerElements-iron-collapse/1.0.4/iron-collapse.html
fails to load, because it tries to load ../polymer/polymer.html.

**Comment by iphydf** [comment]
Here is what I did to solve the problem for my app: https://github.com/iphydf/webtox/blob/master/project/WebJarsSymlinks.scala

**Comment by jamesward** [comment]
Unfortunately I don't think we can fix this with Bower WebJars.  The Polymer project has not registered all of their packages in the Bower repo.  Because of this we have to determine an artifactId based on the git url.  And the way Polymer uses cross-project relative references seems like an anti-pattern to me.  With RequireJS you can override paths with configuration.  That'd be a better approach for dependency loading.
