### ISSUE TITLE
seiyria-bootstrap-slider bower webjar contains dependencies

### ISSUE THREAD

**Issue by Spitemare** [webjars/webjars#1267]
org.webjars.bower:seiyria-bootstrap-slider:5.2.6 contains a dependencies folder containing the files jquery.min.js, modernizr.js, and bootstrap.min.css. This causes webjars-locator to throw a MultipleMatchesException when trying to locate any of these files if bootstrap or jquery webjars also exist on the classpath.

**Comment by jamesward** [comment]
Ideally the `dependencies` folder shouldn't be there since the whole point of a package manager is to not have to put dependencies inside of artifacts.  But this will have to be fixed upstream.

In the meantime you can use `locator.getFullPathExact("artifact", "path")` instead to avoid the multiple matches.  More details: https://github.com/webjars/webjars-locator-core#obtain-the-full-path-of-an-asset
