### ISSUE TITLE
WebJar for lrsjng/jquery-qrcode

### ISSUE THREAD

**Issue by sergiuszkierat** [webjars/webjars#1308]
>Failed!
> Server returned HTTP response code: 500 for URL: https://bower-as-a-service.herokuapp.com/download/jquery.qrcode/0.12.0

Bower as a service for [GET info/jquery.qrcode/0.12.0](https://bower-as-a-service.herokuapp.com/info/jquery.qrcode/0.12.0) returns repository.url /**lrsjng**/jquery-qrcode.git, which is OK.

On the other hand,  an exception
> No versions found in git://github.com/gcusnieux/jquery-qrcode.git

points to /**gcusnieux**/jquery-qrcode.git during a deploy step.

**Comment by jamesward** [comment]
This one is strange.  I think that the name of the package is being screwed up by their metadata:
https://bower-as-a-service.herokuapp.com/info/jquery.qrcode/0.12.0

See how the name is set to `jquery-qrcode` there?  I guess I'm using that name instead of the provided one.  I'll look into this.  In the meantime, I've deployed this using the git-based deployment:
```
GroupID = org.webjars.bower
ArtifactID = github-com-lrsjng-jquery-qrcode
Version = 0.12.0
```

**Comment by sergiuszkierat** [comment]
Firstly, thanks for an artifact. I use [it](https://github.com/sergiuszkierat/blog-2FA/commit/0d808d3735bdb8fd0a5f9d4935b92302ee18bedc).

Secondly, I am looking forward to seeing a bugfix.

**Comment by jamesward** [comment]
This has been fixed: https://github.com/jamesward/bower-as-a-service/commit/0b6674d39e0e70fe9c2094b28ec7e2fa1d59aab0

The WebJar is now available:
```
GroupID = org.webjars.bower
ArtifactID = jquery.qrcode
Version = 0.12.0
```

**Comment by sergiuszkierat** [comment]
Thanks a lot.
