### ISSUE TITLE
UIKit Bower WebJar fails to upgrade itself

### ISSUE THREAD

**Issue by nayzak** [webjars/webjars#1309]
Current version of Bower WebJar for UIKit is 2.20.3. I tried to deploy a new version (2.24.3), but process fails with license error. It says that no bower.json, no git repo contains license information. I checked older versions of UIKit and found out that it's bower repo didn't change its structure and bower.json file since 2.20.3 version. So what should I do next? It's obvious that older versions of bower package of UIKit didn't contain any license info, but they are available at webjars.org.

**Comment by jamesward** [comment]
Their `bower.json` doesn't specify a license: https://bower-as-a-service.herokuapp.com/info/uikit/2.24.3

So we try to fetch a license file from the git repo, but one doesn't exist there.  Since the license can't be determined programmatically, this will have to be fixed upstream.

I'm not sure how we ever got this package deployed.  Perhaps there was a bug that defaulted to a license.
