### ISSUE TITLE
Please include the following 4 NPM webjars

### ISSUE THREAD

**Issue by schmitch** [webjars/webjars#1318]
Hello, currently the following webjars make an error while trying to deploy them via webjars.org/npm:

    [error] unresolved dependency: org.webjars.npm#ripemd160;0.2.0: not found
    [error] unresolved dependency: org.webjars.npm#indexof;0.0.1: not found
    [error] unresolved dependency: org.webjars.npm#babel-plugin-transform-regenerator;[6.3.13,7): not found

babel-plugin-transform-regenerator has the following error:
```
Failed! The source repository for babel-plugin-transform-regenerator 6.3.13 could not be determined but is required to published to Maven Central. This will need to be fixed in the project's package metadata. If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Determined Artifact Name: babel-plugin-transform-regenerator Starting Deploy
```

However the source code lies in https://github.com/babel/babel (https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-regenerator)

indexof fails with:
```
Failed! The source repository for indexof 0.0.1 could not be determined but is required to published to Maven Central. This will need to be fixed in the project's package metadata. If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Determined Artifact Name: indexof Starting Deploy
```

Not sure if there is a source for that? Could be that: https://github.com/component/indexof

rpiemd160 (0.2.0) fails with:
```
Failed! All attempts to determine a license have been exhausted. The bower.json did not contain a spec-compliant license definition and the license could not be determined by trolling through the GitHub repo. This problem will likely need to be resolved by working with the library maintainers directly. If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Determined Artifact Name: ripemd160 Starting Deploy
```

Currently newer versions work, however for webpack, babel-loader I need version 0.2.0 
License BSD-3 https://github.com/crypto-browserify/ripemd160

Could you please include them? P.S. it would be great if there would be a Command Line Tool for easy packaging, like if something is missing you got asked for it Where is source, Specify license, etc.

Edit Missed:

tapable 0.1.8
```
Failed! The source repository for tapable 0.1.8 could not be determined but is required to published to Maven Central. This will need to be fixed in the project's package metadata. If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Determined Artifact Name: tapable Starting Deploy
```

**Comment by jamesward** [comment]
Welcome the the messy world of NPM package metadata.  :)

We depend fully on the upstream metadata and won't do any overrides because it becomes a maintenance burden.  So these issues will likely have to be fixed upstream.

For `babel-plugin-transform-regenerator` the [repository](https://docs.npmjs.com/files/package.json#repository) section is needed in the metadata.

Unfortunately the `indexof` `0.0.1` package is also [missing the repository section](https://github.com/component/indexof/blob/0.0.1/package.json), but newer versions seem to have it.

As you noticed the license is missing from the version of `rpiemd160` that you need.  So you'll likely need a newer version of the parent package the depends on a newer `rpiemd160`.

Ditto a newer version for `tapable` that includes the necessary metadata.
