### ISSUE TITLE
Correct lookup order for detection of Apache-2.0 license for Bower WebJars

### ISSUE THREAD

**Issue by bartolom** [webjars/webjars#1365]
Dear Webjars Team I failed to create a "Bower Webjar" for https://github.com/vaadin/vaadin-grid 

The protocol looks like this:

```
Failed! 
No valid licenses found. Detected licenses: 
Apache License 2.0 The acceptable licenses on BinTray are at: 
https://bintray.com/docs/api/#_footnote_1
License detection first uses the package metadata (e.g. package.json or bower.json) 
and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the 
master branch of the GitHub repo. 
Since these methods failed to detect a valid license you will need to 
work with the upstream project to add discoverable license metadata 
to a release or to the GitHub repo.  

If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  

Created Bower WebJar 
Fetched Bower zip 
Generated POM 
Converted dependencies to Maven 
Got Bower info 
Determined Artifact Name: vaadin-grid 
Starting Deploy
```

I have detected that the vaadin-grid developers have an unusual paragraoh order in their LICENSE file and I have created a ticket in their issue tracker: https://github.com/vaadin/vaadin-grid/issues/339

But it is a bit odd, because of the webjar protocol line: 
```
License detection first uses the package metadata (e.g. package.json or bower.json) 
and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file
```

because they have the correct line in their bower.json and package.json 
```
"license": "Apache-2.0",
```
https://github.com/vaadin/vaadin-grid/blob/bba275e9d618a2d184e3eeb7e44fdc524ffcf9e9/package.json

So maybe the webjars generator does *first* test the LICENSE file and not bower.json and package.json.

If current behaviour is as expected, maybe one could just make the logging line less ambigious.

**Comment by jamesward** [comment]
The problem is that the `bower.json` and `package.json` contain an invalid SPDX license identifier in `1.0.0`:
https://github.com/vaadin/vaadin-grid/blob/1.0.0/bower.json#L7
https://github.com/vaadin/vaadin-grid/blob/1.0.0/package.json#L6

This has been fixed since `1.0.0` but we will need a new tagged release for it to work with Bower / NPM WebJars.

The fallback to `LICENSE` on `master` should be working because the license is properly identified:
https://github-license-service.herokuapp.com/vaadin/vaadin-grid

But I think we may not be using the fallback since the license was specified in metadata.  It was just invalid.  That might be something we can fix.

**Comment by bartolom** [comment]
Thank you for looking into this. I'll update https://github.com/vaadin/vaadin-grid/issues/339 and let the Vaadin team know about findings.

**Comment by bartolom** [comment]
The Vaadin team have fixed the issue, and ai the mantime someone already successfully deployed vaadin-grid 1.1.0 and 1.1.1 to webjars.org.

Thank you for the SPDX hint
