### ISSUE TITLE
angular2 npm modules can't be imported automatically anymore

### ISSUE THREAD

**Issue by joost-de-vries** [webjars/webjars#1399]
With angular2 RC0 the Angular npm modules no longer have a "repository" field in their package.json
And as a result it's no longer possible to automatically add them to webjars.org/npm

Unfortunately the angular team is not willing to fix that [issue](https://github.com/angular/angular/issues/8571)

So how can we publish these npm modules most easily anyway? I foresee quite a few new versions coming up in the near future. 

Can I lend a helping hand in some way?

**Comment by jamesward** [comment]
I responded to the issue you created against `angular2`.  It is unfortunate that they don't specify the `repository` but unfortunately that is required metadata for Maven Central.  So I'm not sure what we can do about this.

**Comment by jamesward** [comment]
BTW, this is an issue with a number of other libs too.  Like: https://github.com/webjars/webjars/issues/1392

**Comment by joost-de-vries** [comment]
Thanks for your help on the issue with angular2. I agree that it is very disappointing that they show no interest in providing basic metadata like a good npm ecosystem citizen.
Let's see if we can change their minds.

**Comment by joost-de-vries** [comment]
Btw you're really fast in responding! :-)

**Comment by joost-de-vries** [comment]
The issue was reopened and I made a pull request. 
So this issue can be closed for now.

Thanks for your help James.

**Comment by jamesward** [comment]
@joost-de-vries BTW: You can deploy git repos instead of using the NPM artifacts to workaround this.  I just deployed https://github.com/angular/platform-browser-dynamic-builds.git and since it was deployed form the git repo we know that metadata.  The only downside is that we can't use the nice artifact name because we can't guarantee it is the right one.  So the artifact Id for that one is `github-com-angular-platform-browser-dynamic-builds` and the version comes from `package.json` which for some reason is `0.0.0-PLACEHOLDER`.

**Comment by joost-de-vries** [comment]
I've submitted a PR for the module within the `angular/angular` repo. Strange that there's a separate repo as well.
It's good to have the alternative you mention. Cool.

**Comment by joost-de-vries** [comment]
I notice you already submitted the same PR. :-) I've closed mine.
