### ISSUE TITLE
Can't deploy toastr

### ISSUE THREAD

**Issue by donbeave** [webjars/webjars#1434]
Deploy Log
```
Failed!
All attempts to determine a license have been exhausted. The bower.json or package.json did not contain a spec-compliant license definition and the license could not be determined by trolling through the GitHub repo. This problem will likely need to be resolved by working with the library maintainers directly.

If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Determined Artifact Name: toastr
Starting Deploy
```

But actually `package.json` already contains license information (https://github.com/CodeSeven/toastr/blob/master/package.json):
```
  "licenses": [
    {
      "type": "MIT",
      "url": "http://www.opensource.org/licenses/mit-license.php"
    }
  ],
```

**Comment by jamesward** [comment]
Bower or NPM?  What version?  I deployed 2.1.2 via NPM WebJars without any issues.

**Comment by donbeave** [comment]
Bower.
Version: 2.1.2.

**Comment by jamesward** [comment]
The Bower metadata is in the `bower.json` file and the backing repo for that package is: https://github.com/johnpapa/toastr-bower

There isn't a license specified in that repo's `bower.json`: https://github.com/johnpapa/toastr-bower/blob/master/bower.json

So this will need to be fixed upstream.

Side note: The error message could be better since it can be confused as saying that we use both Bower and NPM metadata when we actually only use the metadata for the specified type of WebJar.  So I'm going to leave this open until we fix that.

**Comment by TimFerrell** [comment]
Am I to assume no further action needed because of the closure?

**Comment by donbeave** [comment]
@TimFerrell, this task was closed because problem not on the webjars side, and actually commit above just added more concrete information about license problem. But you still need to add license information to bower.json file in your repository, I also created a PR: https://github.com/johnpapa/toastr-bower/pull/9
