### ISSUE TITLE
Discrepancy between webjar version and content

### ISSUE THREAD

**Issue by ncelerier** [webjars/webjars#1549]
Hello, 

See the first message of this issue: 
https://github.com/corinis/jsForm/issues/14

I have selected version 1.3.5 to create the webjar, but in bower.js version 1.3.2 was specified. So the uploaded webjar specify version 1.3.2, but the content of the webjars is the one of version 1.3.5.

So there is a discrepancy between webjar version and content.

To avoid this I think it would be nice to add a confirm button before uploading a Bower webjar to Maven central, or checking that the selected version match the version of the webjar.

What do you think ?

**Comment by jamesward** [comment]
I think this is specific to deploying the git repo, instead of the Bower artifact.  I've just deployed `jquery-jsform` version `1.3.5` and it seems like everything worked as expected.  When you use the git repo, to deploy we do use the version from the `bower.json` instead of the specified tag.  I'm not sure why we do that but it seems like there was a reason for it...

Anyways, let me know if that provides what you need.

**Comment by ncelerier** [comment]
I see that you have created the new webjar jquery-jsform using "Bower package name" instead of "Git Repo URL". And it seems correct indeed.

But, when you deploy using the git repo, shouldn't the dialog be updated so that we don't have to choose a version ? Since it won't be taken into account anyway ? Maybe a little help message could be added too to describe what will happen.

**Comment by jamesward** [comment]
The version is used to figure out what point-in-time to use in the git repo.  But if the `bower.json` has a version that doesn't match the selected tag, then we don't do anything to prevent that discrepancy.  We have 3 options for what we could do when there is a discrepancy:
1. Use the `bower.json`
2. Use the selected git version
3. Throw an error

I think we chose to do 2 because these versions are used in transitive dependencies and we need to be able to handle that.  But the side effect of this is that multiple points-in-time can point to a single version (based on `bower.json`).  So this isn't ideal but there is only so much we can do when dealing with flimsy package managers.
