### ISSUE TITLE
Cannot deploy 'atob' NPM package

### ISSUE THREAD

**Issue by BuryakVladimir** [webjars/webjars#1674]
It's my log:

**Comment by BuryakVladimir** [comment]
`Failed!
Could not get the current URL for https://github.com/coolaj86/node-browser-compat/atob because status was Not Found
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Determined Artifact Name: atob
Deploying org.webjars.npm atob 2.0.0
Starting Deploy`

**Comment by BuryakVladimir** [comment]
I need NPM webjar with 'org.webjars.npm:atob:2.0.0'

But when i use new url: https://github.com/node-browser-compat/atob
I have next webjar 'org.webjars.npm:github-com-node-browser-compat-atob:2.0.0' 

I have created request before: WebJar Request: atob #1673

**Comment by jamesward** [comment]
I think the problem is that the repository url specified in the package.json isn't a valid git repo:
https://github.com/node-browser-compat/atob/blob/master/package.json#L7

But I was able to manually deploy this.  To make things easier in the future it'd be great if you can work with the project to fix that url.

**Comment by BuryakVladimir** [comment]
Thanks, I try fix that url
