### ISSUE TITLE
License issue when trying to add mapbox-gl-js 2.15.0

### ISSUE THREAD

**Issue by ssjoleary** [webjars/webjars#2014]
Hi, thanks for all your work on webjars.org!

I'm having an issue trying to add a webjar, type NPM, for the project [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js).

The error I'm seeing is:

```
[[31merror[0m] u.LicenseDetector - License fetch error:
...(prints full LICENSE.txt, omitting for brevity)...
License Not Detected
The license could not be determined for NPM - https://github.com/mapbox/mapbox-gl-js v2.15.0
```

The [package.json](https://github.com/mapbox/mapbox-gl-js/blob/main/package.json) for this project has this:
```
{
  "name": "mapbox-gl",
  "description": "A WebGL interactive maps library",
  "version": "2.15.0",
...
  "license": "SEE LICENSE IN LICENSE.txt",
...
}
```

The [LICENSE.txt](https://github.com/mapbox/mapbox-gl-js/blob/main/LICENSE.txt) contains a few licenses for different libraries.

I'm not involved with the `mapbox-gl-js` library, I'm only a user, but I'm wondering if you could point me in the right direction to try and fix this issue? Thanks!

**Comment by jamesward** [comment]
Thanks for filing this.  A little history... We used to deploy to Maven Central through Bintray but no longer do that.  Bintray required an open source license.  So that is the primary reason this exists.  I can do something different now that we deploy directly to Maven Central.  I need to see how the `pom.xml` metadata should specify this kind of license.  I could try to leave the `name` field blank but include the url to the license file.  Would that work for you, if it works with Maven Central?

**Comment by ssjoleary** [comment]
Thanks for the info! That works for me, cheers.

**Comment by jamesward** [comment]
I was able to deploy this with the license reference:
```
GroupID = org.webjars.npm
ArtifactID = mapbox-gl
Version = 2.15.0
```

Let me know if you have any issues.
