### ISSUE TITLE
Deploy failed for @xenova/transformers.js

### ISSUE THREAD

**Issue by thomasht86** [webjars/webjars#2053]
I tried to add a webjar for npm-package [@xenova/transformers.js](https://github.com/xenova/transformers.js/tree/main), but it failed to resolve the dependency graph. 

![image](https://github.com/webjars/webjars/assets/24563696/82257bb2-50c4-43b1-85aa-e043ba8e4407)

Any chance anyone could help/point in the right direction for solving this? 🙏

**Comment by jamesward** [comment]
I made a change recently to dependency resolution and as part of that, `@types/node` was failing to determine the maxSatisfying version because it has a large number of available versions causing it to exceed a query string limit.  I've fixed that by partitioning the maxSatisfying calls.  This change should be deployed in about 10 minutes and should fix this.  Let me know if you have any other issues.  Also, filed an issue on semver-as-a-service: https://github.com/jamesward/semver-as-a-service/issues/1
