### ISSUE TITLE
Automate version update of existing webjars

### ISSUE THREAD

**Issue by cowwoc** [webjars/webjars#289]
The most common request we get is to update a webjar to a new version. We should add a functionality on webjars.org that automates the process of replacing some variable with the requested version number, and attempting to release the new webjar.

We'll still need to manually add new webjars and handle existing webjars if the above process fails, but at least 85% of requests would be automated. At least, that's the theory :)

**Comment by mwanji** [comment]
I just saw that Maven Central has a ["search by tag"](http://search.maven.org/#api) feature. Does anyone know how it works? The documentation is very short and doesn't say how tags are found or created.

This might be a solution: if artifacts can be tagged as a webjar, then they can appear on the site without @jamesward having to manage it all himself. Syncing with bower could be a good solution for artifacts in the org.webjars group, but tagging might allow you to close that group and simply have people manage their own damn webjars ;). After all, plugins for Rails's asset pipeline aren't centralised and they do just fine.

If tags don't work, maybe there could simply be a convention that the word "webjars" appear somewhere in the group ID.

James: I think you should promote some of these automation ideas (bower, conventions...) to their own issues. I feel bad every time I see you dealing with a new/upgrade webjar request.

**Comment by cowwoc** [comment]
@mwanji If you're talking about automating listing webjars on webjars.org, that is already done. If you're talking about automating version updates, I'm not sure how this helps.

**Comment by mwanji** [comment]
My main point is that James shouldn't have to be involved every time a webjar is created or updated.

Currently, the website only lists artifacts in the org.webjars group. If there were another way to aggregate them, eg via tags or some other convention, then people could manage their webjars themselves and still have them show up on webjars.org. And James could "get his Saturdays back." Or, at least, use his time more productively than housekeeping webjars.

On top of that, any bower-driven automation could hopefully be offered for webjars inside and outside of the org.webjars group.

**Comment by jamesward** [comment]
Time consumption with WebJars looks like this:
- Version bump = ~1 minute - ~20x / week
- Fork contributed WebJar = ~5 minutes - ~1x / week
- Create new WebJar = ~10 minutes - ~10x / week

Enabling third party published libs on webjars.org would save a little bit of time in the current structure.  Right now I'm doing fine with the current workload and it isn't growing much.  I think probably the best way to reduce my workload would be to reduce the time to create new WebJars.  Most of the time is spent looking for the necessary pieces.  Maybe a web form with specific fields, instead of just sending people to a blank GitHub issue would help to reduce the biggest chunk of my workload.

**Comment by cowwoc** [comment]
My problem with letting 3rd-party creation of webjars is that people will screw it up. I know, because I've done so myself. A second factor is that if someone abandons support of a webjar, we can "reclaim" it from them and continue support. If you outsource this work to 3rd-parties you'll end up with a higher error rate and abandoned artifacts that cannot be reclaimed.

I don't know if that's a problem in practice or in theory, but it's worth considering.

That said, maybe it's worth eating this cost in exchange for James getting his Saturdays back :) After all, Maven Central is full of abandoned or error-filed artifacts. This wouldn't be any different.

**Comment by mwanji** [comment]
@jamesward 

> Maybe a web form with specific fields, instead of just sending people to a blank GitHub issue

Or a project to clone, with either inline comments or a README that steps people through the process? That way there's no extra coding to do and it's easier to keep up to date.

In #792 you mention working on the npm sync system. Do you have any more details on that? I was wondering if this is something that would be part of the website or a separate repo. I would be interested in lending a hand, if it's separate and in Java 8, rather than Scala ;). I guess there could end up being modules for each backend webjars.org relies on: npm, bower, maven central.

@cowwoc 

> If you outsource this work to 3rd-parties you'll end up with a higher error rate and abandoned artifacts that cannot be reclaimed.

Isn't this basically how open source works, in general? It's up to the people interested in a webjar to keep it up to date and non-broken. Also, can James actually validate that each and every artifact in org.webjars actually works (ie. contains the correct JS files, will work as expected in a project, etc.)?

**Comment by jamesward** [comment]
Here is all that I've written up on the idea of a Bower sync: https://gist.github.com/jamesward/94c3374c887bf9b4abfe

If we did it for Bower it would be pretty easy to then do it for NPM as well.

**Comment by huntc** [comment]
Thanks James, I'll have a read!

**Comment by jamesward** [comment]
I'd still like to do this for NPM but since we've done this for Bower I'm going to close this issue.  To close the loop for those following, here is the pertinent info:
http://www.jamesward.com/2015/03/23/scaling-the-webjars-project-with-on-demand-bower-packages
https://github.com/webjars/webjars/pull/896
https://github.com/webjars/webjars/pull/927
