### ISSUE TITLE
WebJars contribution

### ISSUE THREAD

**Issue by cheleb** [webjars/webjars#862]
I've just pushed raw webjars for polymers components  https://github.com/cheleb/org.webjars.polymers
It is a raw webjarification of https://github.com/Polymer

**Comment by jamesward** [comment]
Thanks for doing this! Here are a few things we need to change with this:
* This should be a pull request against the existing `polymer` WebJar: https://github.com/webjars/polymer
* Stick with `org.webjars` for the `groupId`
* I'd like to use the name from the `bower.json` as the `artifactId` but I can't tell if this would introduce naming conflicts because it doesn't look like they have actually published these libs to Bower.  If this would introduce conflicts then the `artifactId` could be `polymer-NAME` but maybe we should ask the upstream maintainers what they plan to do about naming to fit these into NPM / Bower.
* We need to use Maven `-SNAPSHOT` versioning for the project version since Maven does the actual release.
* Make sure the build actually runs correctly.  When I tried the existing build it failed.

**Comment by cheleb** [comment]
On Sun, Feb 22, 2015 at 9:10 PM, James Ward <notifications@github.com>
wrote:

> Thanks for doing this! Here are a few things we need to change with this:
>
>    - This should be a pull request against the existing polymer WebJar:
>    https://github.com/webjars/polymer
>
> You realise that this might be a massive PR ?

   1. The root pom will became a "pom" packaging
   2. Underneath ~ 130 child module with each a webjar.


>    -
>    - Stick with org.webjars for the groupId
>
> Ok, I was just afraid that this groupId will be bloated :)

>
>    -
>    - I'd like to use the name from the bower.json as the artifactId but I
>    can't tell if this would introduce naming conflicts because it doesn't look
>    like they have actually published these libs to Bower. If this would
>    introduce conflicts then the artifactId could be polymer-NAME but
>    maybe we should ask the upstream maintainers what they plan to do about
>    naming to fit these into NPM / Bower.
>
> As far a can I try to stick to the bower.json file (when it is present :-/
)

>
>    - We need to use Maven -SNAPSHOT versioning for the project version
>    since Maven does the actual release.
>
> Which one ? The root one or all of them ?

>
>    - Make sure the build actually runs correctly. When I tried the
>    existing build it failed.
>
> Sure :-/

>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webjars/webjars/issues/862#issuecomment-75454890>.
>



-- 
"Computers are useless. They can only give you answers."
- Pablo Picasso -

**Comment by jamesward** [comment]
Sounds good.  I don't mind a massive PR.

**Comment by cheleb** [comment]
Not sure what to do about the SNAPHOT ...
For the moment, I use the last release tag of each component to find the
version.


On Sun, Feb 22, 2015 at 10:15 PM, James Ward <notifications@github.com>
wrote:

> Sounds good. I don't mind a massive PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webjars/webjars/issues/862#issuecomment-75459569>.
>



-- 
"Computers are useless. They can only give you answers."
- Pablo Picasso -

**Comment by jamesward** [comment]
The `<version>` in the `pom.xml` needs to be `UPSTREAM_VERSION-SNAPSHOT` because Maven does the actual release (removes the `-SNAPSHOT` and tags git, etc).

**Comment by jamesward** [comment]
Closing this issue in favor of the PR.

**Comment by chevdor** [comment]
Was there ever a PR for that?

**Comment by jamesward** [comment]
Here is the PR: https://github.com/webjars/polymer/pull/8

It lost momentum since the maintenance burden of this tree of Classic WebJars is massive.  Using Bower or NPM WebJars is a much easier way to go.

**Comment by chevdor** [comment]
OK I was hoping for an option to help solving #1249 
Thanks for the feedback.

**Comment by jamesward** [comment]
You are definitely free to help get that PR or a new one to a better state.
