### ISSUE TITLE
WebJars flat layout

### ISSUE THREAD

**Issue by cheleb** [webjars/webjars#866]
(I've already post the question in http://stackoverflow.com/questions/28657435/webjars-flat-gav-layout)
Is there a reason to adopt a flat layout in GAV of webjars ? I mean, all groupId are set to "org.websjars". I like to contribute to webjars with polymer elements (core & paper). Its about 132 artifacts (230 with labs & deprecated) ... I would like to use groupId like:

org.webjars.polymers.polymer
org.webjars.polymers.core
org.webjars.polymers.paper
org.webjars.polymers.misc
org.webjars.polymers.labs
org.webjars.polymers.deprecated

Good or bad idea / practice ?

Thanks

**Comment by jamesward** [comment]
We've always used just `org.webjars` since there isn't a concept of a groupId in JS package repositories. That way the `artifactId` can correspond to the NPM / Bower artifact name. The only plans we have for using a different groupId are when we do a Bower sync where we'd make the `groupId` = `org.webjars.bower`.  I've also commented about this on #862 so lets continue the discussion there or in a PR against the existing `polymer` WebJar.
