### ISSUE TITLE
Dead Bower Index Handling

### ISSUE THREAD

**Issue by gabadi** [webjars/webjars#945]
When i try to create a new bower webjar, during the github repositories fetch i always get a: Loading failed

Thanks in advance, the project is amazing

**Comment by tscheinecker** [comment]
the server returns a status code 500 for all requests...
http://www.webjars.org/_bower/packages?query&page=1

**Comment by jamesward** [comment]
It looks like the Bower service has been intermittent the past few days possibly due to the DDOS against GitHub.  The Bower index doesn't seem to be working at the moment: http://bower.io/search/

So there isn't much we can do.  But I should provide some better error handling so I'll leave this open.

**Comment by gabadi** [comment]
Ok, thank you

**Comment by jamesward** [comment]
For reference this is the Bower issue for this: https://github.com/bower/search/issues/67

**Comment by gabadi** [comment]
Is working again
