### ISSUE TITLE
504 for underscore from jsDelivr

### ISSUE THREAD

**Issue by khy** [webjars/webjars#980]
Not sure if this is the right place for this, but for at least 10 minutes the following URL was returning a 504: `https://cdn.jsdelivr.net/webjars/underscorejs/1.7.0/underscore-min.js`. It has since fixed itself.

Maybe this belongs in sbt-web as it seems to use this jsDelivr by default? Either way, I can't really use this CDN as this outage totally broke my site - luckily it's just a personal project.

**Comment by jimaek** [comment]
504 errors means that the origin server didnt respond. Its not a jsDelivr error but a webjars one.

**Comment by jimaek** [comment]
@jamesward Ping about your origin server. Can we do anything to improve uptime? I believe its still having issues

**Comment by jamesward** [comment]
Oddly I'm not seeing any errors in the webjars.org log for that file.  And right now it seems to be working fine:
http://www.webjars.org/files/underscorejs/1.7.0/underscore-min.js

So I'm not sure what the problem was.

At some point the backing service for the CDN should be static file based instead of being part of the webjars.org app.  So I'm going to leave this open.

**Comment by jimaek** [comment]
@jamesward I will email you the IP the server is hitting. Its timing out. Maybe its a firewall issue?

**Comment by jamesward** [comment]
Thanks @jimaek.  Strange thing is that I'm not seeing those requests in my logs.  And oddly requests from the CDN seem to have stopped coming in for a long time last night:
```
Apr 21 16:34:21 webjars heroku/router:  at=info method=GET path="/files/bootstrap/3.3.4/js/bootstrap.min.js" host=www.webjars.org request_id=6ecad25e-20b9-4233-bd84-c273da25adeb fwd="104.131.239.42" dyno=web.1 connect=2ms service=29ms status=200 bytes=36199 
Apr 22 05:45:18 webjars heroku/router:  at=info method=GET path="/files/underscorejs/1.7.0/underscore-min.js" host=www.webjars.org request_id=570002d7-a019-4904-9f03-c121fb3766e7 fwd="76.89.92.16" dyno=web.1 connect=1ms service=135ms status=200 bytes=5595 
```

Heroku's router / load balancer logs any incoming requests and we should be seeing a lot of requests in that time period but didn't.  Interestingly a minute ago a bunch of requests started coming in from the CDN.

So I'm not sure what is going on.  But looking at the request logs on your side I'm a little worried about the IP in the request: `http://54.235.124.102:80/files/select2/3.5.2/select2.min.js`

Perhaps the name resolution is being cached for too long?

**Comment by jimaek** [comment]
Probably, that seems to be the problem. It appears that your Heroku instance failed or something and changed the IP. The server on our side didnt pick up the change because of DNS TTL so our server was hitting the old webjars IP instead of the alive one.
I am not sure that you can control your DNS TTL but try lowering it to ensure we get the correct IP instantly

**Comment by jamesward** [comment]
Here is my DNS:
```
www.webjars.org.	3600	IN	CNAME	webjars.herokuapp.com.
webjars.herokuapp.com.	300	IN	CNAME	us-east-1-a.route.herokuapp.com.
us-east-1-a.route.herokuapp.com. 28 IN	A	54.243.230.233
```

Looks like I should change my TTL from `3600` to `300` to match the Heroku TTL.  Right?

**Comment by jamesward** [comment]
The lowest that GoDaddy lets me go is `600` so I've made that change but will look into moving DNS to somewhere else that supports `300`.

**Comment by jimaek** [comment]
I recommend NSONE. They can also do DNS load balancing on your origin and lots of other cool stuff.
I will also setup uptime monitoring of your server just in case

**Comment by jamesward** [comment]
I've moved the WebJars file service to:
http://webjars-file-service.herokuapp.com/files

For example:
http://webjars-file-service.herokuapp.com/files/org.webjars/jquery/2.1.0/jquery.js

Since that endpoint doesn't use the webjars.org DNS, once we get that change made on jsDelivr, this issue should go away.

cc @jimaek

**Comment by jimaek** [comment]
@jamesward I made the change, cdn.jsdelivr.net/webjars now points to http://webjars-file-service.herokuapp.com/files

**Comment by jamesward** [comment]
Thanks @jimaek! Looks like everything is still working correctly. :)
