### ISSUE TITLE
jquery-ui package seems to be missing files

### ISSUE THREAD

**Issue by blast-hardcheese** [webjars/webjars#989]
Disclaimer, this could entirely be my own mistake, but without digging into the whole build process, I suspect I'm out of options. This is further complicated by the fact that I've got four other webjars that work perfectly.

To start off, I'm using

- Scala 2.11.1
- Play 2.3.8
- WebJars 2.3.0-3

I've included the following webjar:

    "org.webjars.bower" % "jquery-ui" % "1.11.4"

`conf/routes` contains

    GET    /webjars/*file    controllers.WebJarAssets.at(file)

In my templates, I've got

    <script type='text/javascript'
            src='@routes.WebJarAssets.at(WebJarAssets.locate("jquery-ui.js"))'></script>

which renders to 

    <script type='text/javascript' src='/webjars/jquery-ui/1.11.4/jquery-ui.js'></script>

and produces

    GET http://localhost:9001/webjars/jquery-ui/1.11.4/jquery-ui.js

when loaded in Chrome.

Thanks in advance!

**Comment by jamesward** [comment]
What is the error?

**Comment by blast-hardcheese** [comment]
No error, the file is just not there. I'm trying to follow the jquery-ui quickstart, but it looks like (my guess is) all that ends up packaged are component files, not the primary include. Not sure if this is on purpose, or a result of an incomplete build process.

Thanks!

**Comment by jamesward** [comment]
I see.  That WebJar points to:
https://github.com/jquery/jquery-ui/tree/1.11.4

You can grab the jar from:
https://bintray.com/artifact/download/webjars/maven/org/webjars/bower/jquery-ui/1.11.4/jquery-ui-1.11.4.jar

And see what is in there.

So yes, there isn't the file you are looking for in that WebJar.  Maybe you should create a Bower WebJar for the `jqueryui` library instead since that one seems to be what you are looking for.

**Comment by blast-hardcheese** [comment]
The problem is more that the jquery-ui repo requires a grunt command to build those files. Is there any plan for supporting custom grunt steps during the build process?

**Comment by jamesward** [comment]
I definitely could make the Bower WebJar creator run the Grunt build but I'm not sure if I should do that.  Some questions:
- How do I know if I should run the Grunt build on a project?  Should I always do it if a `Gruntfile.js` exists?
- Is there a reason to not run the Grunt build?  Are there times when the user wants the source assets instead of the compiled assets?
- How do users of this Bower package work?  Do they `bower install jquery-ui` and then manually run Grunt?
- Will I need to run Gulp builds for Gulp projects as well?  What about other build tools?

Thanks for helping me think through this.

**Comment by blast-hardcheese** [comment]
Given the way the build environment currently works, are build tools like grunt downloaded (as grunt and its plugins are listed under devDependencies for the package)?

What seems beneficial to the project at large would be avoiding build-time customization, since if someone can enter any command in the "Deploy" box, they can screw up the build for everyone.

That being said, would it make sense to have some logic that would check the dependencies for cues of which commands to run (in this case, grunt-contrib-concat suggests `grunt concat`, which seems supported by the readme)? It wouldn't do anything different if the build tool isn't in the figure-out-what-to-do heuristic, so there's no danger of breaking the build, and it would encourage contributions from people who want to use a project with a particular build system.

Downsides of this approach would be increased load on the build servers, possible build failures, incorrect heuristics being applied, and a dependency on a JavaScript interpreter, which may or may not exist currently.
