### ISSUE TITLE
WebJar Request: oclazyload

### ISSUE THREAD

**Issue by njovy** [webjars/webjars#990]
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.sonatype.oss</groupId>
        <artifactId>oss-parent</artifactId>
        <version>7</version>
    </parent>
    
    <packaging>jar</packaging>
    <groupId>org.webjars</groupId>
    <artifactId>oclazyload</artifactId>
    <version>1.0.0-beta.2-SNAPSHOT</version>
    <name>ocLazyLoad</name>
    <description>WebJar for ocLazyLoad</description>
    <url>http://webjars.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <upstream.version>1.0.0-beta.2</upstream.version>
        <upstream.url>https://github.com/ocombe/ocLazyLoad/archive/v${upstream.version}.zip</upstream.url>
        <destDir>${project.build.outputDirectory}/META-INF/resources/webjars/${project.artifactId}/${project.version}</destDir>
        <requirejs>
            {
                "paths": {
                    "oclazyload": "ocLazyLoad"
                },
                "shim": {
                    "oclazyload": ["DEP_ID"]
                }
            }
        </requirejs>
    </properties>

    <developers>
        <developer>
            <id>njovy</id>
            <name>Taehyun Park</name>
            <email>root@njovy.com</email>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>MIT</name>
            <url>https://github.com/ocombe/ocLazyLoad/blob/master/LICENSE.md</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <url>http://github.com/webjars/oclazyload</url>
        <connection>scm:git:https://github.com/webjars/oclazyload.git</connection>
        <developerConnection>scm:git:https://github.com/webjars/oclazyload.git</developerConnection>
        <tag>HEAD</tag>
    </scm>
    
    <dependencies>
        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>ANOTHER_WEBJAR_ARTIFACT_ID</artifactId>
            <version>ANOTHER_WEBJAR_ARTIFACT_VERSION</version>
        </dependency>
    </dependencies>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.7</version>
                <executions>
                    <execution>
                        <phase>process-resources</phase>
                        <goals><goal>run</goal></goals>
                        <configuration>
                            <target>
                                <echo message="download archive"/>
                                <get src="${upstream.url}" dest="${project.build.directory}/${project.artifactId}.zip"/>
                                <echo message="unzip archive"/>
                                <unzip src="${project.build.directory}/${project.artifactId}.zip" dest="${project.build.directory}"/>
                                <echo message="moving resources"/>
                                <move todir="${destDir}">
                                    <fileset dir="${project.build.directory}/${project.artifactId}-${upstream.version}"/>
                                </move>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>2.5.1</version>
            </plugin>

            <plugin>
                <groupId>org.sonatype.plugins</groupId>
                <artifactId>nexus-staging-maven-plugin</artifactId>
                <version>1.6.5</version>
                <extensions>true</extensions>
                <configuration>
                    <serverId>sonatype-nexus-staging</serverId>
                    <nexusUrl>https://oss.sonatype.org/</nexusUrl>
                    <autoReleaseAfterClose>true</autoReleaseAfterClose>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>

```

**Comment by jamesward** [comment]
I've published a Bower WebJar for this:
```
GroupID = org.webjars.bower
ArtifactID = ocLazyLoad
Version = 1.0.0-beta.2
```

**Comment by RBleyenberg** [comment]
i believe the following is wrong tho, within the pom you've

    <dependencies>
        
        <dependency>
            <groupId>org.webjars.bower</groupId>
            <artifactId>angular</artifactId>
            <version>[1.2.0,1.4.0]</version>
        </dependency>
        
    </dependencies>


at line      <artifactId>angular</artifactId>  angular needs to be angularjs i think.

at this moment i'm getting Unexpected exception where it's trying to find angular.

but webjars angular uses angularjs as id.

Best Regards,

**Comment by jamesward** [comment]
There is a Bower WebJar with that `artifactId` so it should be ok.

**Comment by RBleyenberg** [comment]
i understand, tho one comment;

i'm trying to use ocLazyLoad with router-ui-extra, this package comes from webJar.org under id angularjs, same as all other jars for angular there. and due to the fact that within webJars.bower there id is angular, it gives this expection within sbt for scala. 

So i guess me point is maybe make it one on one with webJars id's as in angularjs, so we can use both libraries. (router-ui-extras is for example not within webjars.bower atm). 

Hope it makes sense,

**Comment by jamesward** [comment]
What is the sbt exception?

Yes, it would probably help to create a `router-ui-extras` Bower WebJar.

**Comment by RBleyenberg** [comment]
router-ui-extras will fix it for me yes. but will not fix cross library code.

Here what i do,
Following without lazyLoad and works

jsDependencies ++= Seq(
  "org.webjars" % "angularjs" % "1.4.0-rc.1" / "angular.js",
  "org.webjars" % "angularjs" % "1.4.0-rc.1" / "angular-animate.js" dependsOn "angular.js",
  "org.webjars" % "angularjs" % "1.4.0-rc.1" / "angular-aria.js" dependsOn "angular.js",
  "org.webjars" % "angular-material" % "0.9.0" / "angular-material.js" dependsOn "angular.js",
  "org.webjars" % "angular-ui-router" % "0.2.14" / "angular-ui-router.js" dependsOn "angular.js",
  "org.webjars" % "ui-router-extras" % "0.0.13" / "ct-ui-router-extras.js" dependsOn "angular-ui-router.js",
  RuntimeDOM),

Then with lazyLoad

jsDependencies ++= Seq(
  "org.webjars" % "angularjs" % "1.4.0-rc.1" / "angular.js",
  "org.webjars" % "angularjs" % "1.4.0-rc.1" / "angular-animate.js" dependsOn "angular.js",
  "org.webjars" % "angularjs" % "1.4.0-rc.1" / "angular-aria.js" dependsOn "angular.js",
  "org.webjars" % "angular-material" % "0.9.0" / "angular-material.js" dependsOn "angular.js",
  "org.webjars" % "angular-ui-router" % "0.2.14" / "angular-ui-router.js" dependsOn "angular.js",
  "org.webjars" % "ui-router-extras" % "0.0.13" / "ct-ui-router-extras.js" dependsOn "angular-ui-router.js",
  "org.webjars.bower" % "ocLazyLoad" % "0.6.3" / "angular-ui-router.js" dependsOn "angular-ui-router.js",
  RuntimeDOM),

and the following expection, which i believe is due to the fact that webJars.bower is on id angular.

JSLibResolveException: Some references to JS libraries could not be resolved:
- Ambiguous reference to a JS library: angular.js
  Possible paths found on the classpath:
  - META-INF/resources/webjars/angularjs/1.4.0-rc.1/angular.js
  - META-INF/resources/webjars/angular/1.4.0-rc.1/angular.js
  originating from: frontend:compile, frontend:compile, frontend:compile, frontend:compile, frontend:compile, frontend:compile

Hope it helps.

**Comment by jamesward** [comment]
Yeah, you have two WebJars with a `angular.js` file.  So you need to get that down to one.  Because the transitive deps you will probably have to specify the Bower WebJar and then manually exclude the transitive from the Classic WebJars that depend on Angular.

**Comment by RBleyenberg** [comment]
thx for that answer, will look into that workflow.

As far as this goes then, without excluding, it's either router-ui-extras within webJar.bower or ocLazyLoad within webJar library that will sort out this setup.

**Comment by dstibbe** [comment]
What kind of nonsens is this: 3 branches: classic, npm and bower, each with their own angular.js , causing nothing but problems (especially realing to angular) . Even worse:  the classic "org.webjars" % "angular-loading-bar" depends on angularjs, which provides not only angular.js , but also angular-material etc etc.... why is this allowed?

**Comment by jamesward** [comment]
@dstibbe Feel free to send pull requests to any of the Classic WebJars that you feel have issues.

**Comment by dstibbe** [comment]
The problem is not the classic. The problem is the three sperate  'branches'  providing their own angular.js. This should be reduced to 1 instead of 3.

**Comment by jamesward** [comment]
They are really 3 separate Maven Central based JS repository systems.  Which is less than exists in the JS repository world.  :)  I wish it could be only 1 but that isn't possible with multiple upstream repositories.
