### ISSUE TITLE
RequireJS configs for Bower packages

### ISSUE THREAD

**Issue by asazernik** [webjars/webjars#991]
Feature request.

Not sure how involved of a feature this is, and the copy on webjars.org ("No RequireJS config (at the moment)") indicates that it's on the roadmap; I figured an issue is as good a place as any to ask what's going on with this once so the question isn't asked over and over.

Without zero-touch requirejs support, bower webjars are just too much of a pain for me to use, unfortunately.

**Comment by jamesward** [comment]
Thanks for opening up a place to discuss this.

I haven't spent a lot of time looking into this because Play's sbt-rjs plugin doesn't use the WebJar RequireJS config, the configs have been a pain to maintain, and they often don't work for all situations.

The hardest part about this is figuring out an automatic way to determine the config.  I've looked at this a bit and there is the `main` config in the `bower.json` but that would only give us a little bit of info and we might get the name of the module wrong.

If we can always auto-determine the RequireJS config from the `bower.json` then maybe we could have a `webjars-locator` utility that can generate the config at runtime or build-time rather than putting the config into the WebJar (since technically it would already be in there since there is a `bower.json` in the Bower WebJars).

Actually...  Thinking about it more that is the right way to do this.  The `webjars-locator` already parses the `pom.xml` from the WebJar to get the RequireJS config.  So for Bower WebJars it can instead parse the `bower.json` and generate the config from that.  The only challenge is figuring out programmatically what the config should be.  But since it will be in `webjars-locator` instead of in the WebJar it will be easy to iterate on that without having to recreate Bower WebJars.

**Comment by asazernik** [comment]
Hmmm. So I don't know how they solve the package-naming issue, but yeoman/bower-requirejs has a pure-Javascript implementation of RequireJS configuration generation from bower.json under a BSD license, so that's a good reference point - the differences would mostly revolve around the different directory structure of a WebJars installation than a regular bower-managed directory. My impression from a veeeery cursory readthrough is that they trust the 'name' attribute in the description of a dependency in the bower.json, but it's not clear to me how/if they determine the name of the primary package (if such a thing is even required for a working require.js config? I'm kind of new to this stuff.)

**Comment by jamesward** [comment]
Cool.  I'll take a look at how `bower-requirejs` works.

**Comment by jamesward** [comment]
Here is the PR to add support for this to `webjars-locator`: https://github.com/webjars/webjars-locator/pull/79

Let me know what you think.

**Comment by asazernik** [comment]
Took a look - looks good to my (not-experienced-with-bower) eyes. Not sure if you want another set of eyes on it, but the test looks pretty solid to me - I don't think requirejs or bower has any weird features that wouldn't be exercised by this.

**Comment by jamesward** [comment]
Thanks for your review!  This will be released shortly as `0.22`.  After upgrading if you run into any issues please file them on the [webjars-locator](https://github.com/webjars/webjars-locator) project.

**Comment by asazernik** [comment]
A bit delayed, but just wanted to let you know that I've switched over to bower webjars (using webjars-play 2.4.0, which pulls in webjars-locator 0.23) and everything's good. Thanks a lot!
